name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Decode and Save SSH Key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > private_key.pem
        chmod 600 private_key.pem

    - name: SSH into EC2 and Deploy
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
          echo "Connected to EC2"

          # Install Docker if not present
          if ! command -v docker &> /dev/null; then
            echo "Docker not found. Installing Docker..."
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo systemctl enable docker
            sudo systemctl start docker
            echo "Docker installed successfully!"
          else
            echo "Docker is already installed."
          fi

          # Navigate or Clone the Project
          if [ ! -d "$HOME/HR_Agent_API" ]; then
            echo "Cloning the repository..."
            git clone https://github.com/Ray-XXX-eee/HR_Agent_API.git $HOME/HR_Agent_API
          else
            echo "Repository already exists. Pulling latest changes..."
            cd $HOME/HR_Agent_API
            git pull origin main
          fi

          # Stop and Remove Existing Container if Needed
          if docker ps -a --filter "name=hra-api-container" | grep "hra-api-container"; then
            echo "Stopping and removing existing container..."
            docker stop hra-api-container
            docker rm hra-api-container
          else
            echo "No existing container found."
          fi

          # Build and Run Docker Container
          echo "Building Docker image..."
          cd $HOME/HR_Agent_API
          docker build -t hra-api-image .
          echo "Running Docker container..."
          docker run -d -p 8000:8000 --name hra-api-container hra-api-image
          echo "API deployed successfully!"
        EOF
