name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Connect to EC2 and Install Docker if not installed
      run: |
        echo "Connecting to EC2..."
        ssh -o StrictHostKeyChecking=no -i "HRA-API-KEY-AMZN.pem" ubuntu@<YOUR_EC2_IP> << 'EOF'
          echo "Checking if Docker is installed..."
          if ! [ -x "$(command -v docker)" ]; then
            echo "Docker not found. Installing Docker..."
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo systemctl enable docker
            sudo systemctl start docker
            echo "Docker installed successfully!"
          else
            echo "Docker is already installed."
          fi
        EOF

    - name: Deploy Docker Container
      run: |
        echo "Connecting to EC2 for deployment..."
        ssh -o StrictHostKeyChecking=no -i "HRA-API-KEY-AMZN.pem" ubuntu@<YOUR_EC2_IP> << 'EOF'
          # Stop and remove existing container if it exists
          docker ps -a --filter "name=hra-api-container" | grep "hra-api-container" && docker stop hra-api-container || true
          docker ps -a --filter "name=hra-api-container" | grep "hra-api-container" && docker rm hra-api-container || true

          # Navigate to project directory or clone if not available
          if [ ! -d "/home/ubuntu/my_project" ]; then
            echo "Project directory not found. Cloning repository..."
            git clone https://github.com/YOUR_USERNAME/YOUR_REPO.git /home/ubuntu/my_project
          else
            echo "Project directory found. Pulling latest changes..."
            cd /home/ubuntu/my_project
            git pull origin main
          fi

          # Build Docker Image
          cd /home/ubuntu/my_project
          docker build -t hra-api-image .

          # Run Docker Container
          docker run -d -p 8000:8000 --name hra-api-container hra-api-image
          echo "API deployed successfully!"
        EOF
