name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Decode and Save SSH Key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > private_key.pem
        chmod 600 private_key.pem

    - name: SSH into EC2 and Deploy
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
          echo "Connected to EC2"
          
          # Install Git if not installed
          if ! command -v git &> /dev/null; then
            echo "Git not found. Installing Git..."
            sudo yum install -y git || sudo apt-get install -y git
          fi

          # Install Docker if not installed
          if ! command -v docker &> /dev/null; then
            echo "Docker not found. Installing Docker..."
            sudo yum install -y docker || sudo apt-get install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
          else
            echo "Docker is already installed."
          fi

          # Clone the repository if not exists
          if [ ! -d "/home/$USER/HR_Agent_API" ]; then
            echo "Cloning the repository..."
            git clone https://github.com/Ray-XXX-eee/HR_Agent_API.git /home/$USER/HR_Agent_API
          else
            echo "Repository exists. Pulling the latest changes..."
            cd /home/$USER/HR_Agent_API
            git pull origin main
          fi

          # Stop and remove any running container
          docker stop hra-api-container || true
          docker rm hra-api-container || true

          # Build and run Docker
          cd /home/$USER/HR_Agent_API
          docker build -t hra-api-image .
          docker run -d -p 8000:8000 --name hra-api-container \
          -e GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }} \
          -e GROQ_API_KEY=${{ secrets.GROQ_API_KEY }} \
          hra-api-image

          echo "API deployed successfully!"
        EOF
